# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nametag_info <- function(model) {
    .Call('_nametagger_nametag_info', PACKAGE = 'nametagger', model)
}

nametag_load_model <- function(file_model) {
    .Call('_nametagger_nametag_load_model', PACKAGE = 'nametagger', file_model)
}

nametag_annotate <- function(model, x, docid, sentenceid) {
    .Call('_nametagger_nametag_annotate', PACKAGE = 'nametagger', model, x, docid, sentenceid)
}

nametag_train <- function(modelname, file, type, features_file, input_type = "trivial", stages = 1L, iterations = 30L, missing_weight = -0.2, initial_learning_rate = 0.1, final_learning_rate = 0.01, gaussian = 0.5, hidden_layer = 0L, file_holdout = NULL) {
    .Call('_nametagger_nametag_train', PACKAGE = 'nametagger', modelname, file, type, features_file, input_type, stages, iterations, missing_weight, initial_learning_rate, final_learning_rate, gaussian, hidden_layer, file_holdout)
}

